### PR TITLE
Resolve #152: Fix deprecated string interpolation for PHP8.2

### LINKED ISSUE #152: Fix deprecated ${} string interpolation for PHP8.2
Hi everyone! 

After updating to PHP8.2, when running for example `ReadRegistersBuilder::newReadHoldingRegisters()->allFromArray($requests)->build();` 
I am getting a PHP Deprecated Warning 
`'ErrorException' with message 'Using ${var} in strings is deprecated, use {$var} instead' `    

I discovered that ${} string interpolation was deprecated in PHP8.2
[https://www.php.net/releases/8.2/en.php#deprecations_and_bc_breaks](https://www.php.net/releases/8.2/en.php#deprecations_and_bc_breaks)

I will upload a patch that fixes this problem shortly!

Environment:
 - OS: Ubuntu 22.04
 - PHP version: 8.2.8
 - Library version: 3.4.0
 - My error_reporting is set to E_ALL (since PHP8 this is the default value, prior PHP8 was E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED).

### PR DESCRIPTION
**Pull request by leoshtika**

### CODE REVIEW

**Comment by aldas** [comment]
Thanks

**Comment by leoshtika** [comment]
Hi Martti! 

Thanks for the quick merging of the patch.
When is the next release planned because we would like to upgrade our server to PHP8.2?

Regards
Leonard

**Comment by aldas** [comment]
@leoshtika  sorry for it taking so long. I released 3.4.1 https://github.com/aldas/modbus-tcp-client/releases/tag/3.4.1 just now

**Comment by leoshtika** [comment]
Thank you very much @aldas . 
Have a good one!

**Pull request merged**
